spring:
  application:
    name: api-gateway
  profiles:
    default: dev
server:
  port: 4040
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    use-root-path: true
    enabled: true
    config-url: /v3/api-docs/swagger-config
    path: /swagger-ui.html
    urls:
      - url: /api/authentication-autofx/v3/api-docs
        name: authentication-autofx

