version: "3.9"
services:
  authentication-autofx:
    image: authentication-autofx
    container_name: authentication-autofx
    networks:
      - autofx-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_USERNAME: autofx
      MYSQL_PASSWORD: admin2025
      SE: "p6F!9vQxR@8nZ#2LsE4u^J1mY*Bw7tKd"
      D: 180